<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="0" failures="0" finished="true" name="Test Run: 44" tests="1" total_time="Finished in: 49.39 secs."/>
<test location="C:/Users/Automation/Documents/MatchMe/Automation/MatchMe/tests/Test_Case1.py" status="ok" test="Test_Case1.test_01" time="49.39">
<stdout><![CDATA[Staring tests on android
AltUnityServer - could not use port 13001
[Errno 10054] An existing connection was forcibly closed by the remote host
AltUnityServer not running on port 13001, retrying (timing out in 60 secs)...
AltUnityServer - could not use port 13001
[Errno 10054] An existing connection was forcibly closed by the remote host
AltUnityServer not running on port 13001, retrying (timing out in 55 secs)...
AltUnityServer - could not use port 13001
[Errno 10054] An existing connection was forcibly closed by the remote host
AltUnityServer not running on port 13001, retrying (timing out in 50 secs)...
AltUnityServer - could not use port 13001
]]></stdout>
<stderr/>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="MatchMe tests"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
